version: "3.2"
services: 
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    ports: 
      - 27017:27017
    environment: 
      MONGO_INITDB_DATABASE: starwarsapi
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: root